### ISSUE TITLE
Problemas para generar remitos/facturas - Pedidos sin circulo

### ISSUE THREAD

**Issue by MariaLlera** [CiudadFutura/mision#122]
Al actualizar la info de los pedidos arroja error. Nos pasó lo mismo la última vez que facturamos.
El error dice que el usuario 10869 no tiene círculo. Le asigné uno, pero sigue fallando.

**Comment by azacchino** [comment]
Maria, buenas. Como la otra vez, no te deja pq en el pedido no tiene asignado circulo. Ya le force uno, deberías poder facturar. Queda pendiente este bug que permite hacer pedidos sin circulo.
