### ISSUE TITLE
Error al mostrar información del usuario

### ISSUE THREAD

**Issue by azacchino** [CiudadFutura/mision#28]
Julián reportó que el Usuario Coordinador aparece como "Usuario" en la pag de información.

> Esto es lo que te decía hoy. Todes aparecen como usuario  Cuando modificás los datos de la persona que aparentemente coordina (la única que no se puede eliminar), aparece esto

![imagen](https://user-images.githubusercontent.com/10451904/43554282-f14e5756-95c9-11e8-9f32-90408e33ff84.png)

![imagen](https://user-images.githubusercontent.com/10451904/43554314-0c0f1fbc-95ca-11e8-9fc2-b5772212eab1.png)

**Comment by azacchino** [comment]
También durante el ciclo. Como coordinador: Muestra erróneamente q no está abierto el ciclo y no muestra la información de los pedidos de los miembros del círculo.

![imagen](https://user-images.githubusercontent.com/10451904/43688795-284f28bc-98c6-11e8-9a68-b0325c807200.png)

**Comment by nfheredia** [comment]
voy a cerrar este bug, ya que es de la versión anterior de la misión
